[21066] Carbon tracker integration
eProsima/SustainML-Library pull request #46
Opened 2024-05-21 09:29 UTC by JesusPoderoso

2024-08-05 12:32 UTC, Snailed commented
I think we need `onnxruntime` as well as a dependency

2024-11-13 15:18 UTC, Mario-DL requested changes
It seems that the tests fail because of a division by `zero`, we should double check why it is happening, probably because we are using some dummy data

2024-11-20 12:01 UTC, Mario-DL commented
@Snailed, it seems that the github ci platform is not supported by the carbontracker as [this error](https://github.com/eProsima/SustainML-Library/actions/runs/11911094940/job/33191869365?pr=46#step:11:5157) is being thrown. I added a [try-except block in the carbontracker usage](https://github.com/eProsima/sustainml-wp3/compare/a1fffdb40a12b548b9e3748ddf93a49d0e300840...c5247a980296b0e66c4438987134561c5740f73f#diff-d415f4000b40bb7f72a15152f4f82b6bb66b3c1d4be131709b5bf88ed1f59639) but it seems is not enough. Any ideas ?

2025-04-29 05:58 UTC, Mario-DL commented
Tackled by moving the carbontracker to a subprocess

2025-04-29 05:58 UTC, closed without merging